Repository jjpush/ios-project-manager, pull requests merged in 2023-01, with the labels that each got.

#21 12 feature entity model 추가
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager.xcodeproj/xcshareddata/xcschemes/ProjectManager.xcscheme
  ProjectManager/ProjectManager/Source/Common/Utils/Extension/Double+Formatter.swift
  ProjectManager/ProjectManager/Source/Common/Utils/Extension/String+Formatter.swift
  ProjectManager/ProjectManager/Source/Domain/Entities/Task.swift
  ProjectManager/ProjectManager/Source/Domain/Entities/TaskEntity.swift
  ProjectManager/ProjectManager/Source/Domain/Entities/Translater.swift
  ProjectManager/ProjectManagerTests/Common/TaskDummy.swift
  ProjectManager/ProjectManagerTests/Common/TaskEntityDummy.swift
  ProjectManager/ProjectManagerTests/TranslaterTests/TranslaterTests.swift
Labels: ⚙️ feature

#23 feat: TaskRepository 및 MockTaskRepository 구현
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Source/Domain/Interfaces/Repositories/TaskRepository.swift
  ProjectManager/ProjectManagerTests/Common/MockTaskRepository.swift
Labels: ⚙️ feature

#22 feat: DidEndEditTaskDelegate 추가
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditTaskDelegate.swift
Labels: ⚙️ feature

#24 Create use case 추가
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Source/Domain/UseCases/CreateUseCase.swift
  ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditTaskDelegate.swift
  ProjectManager/ProjectManagerTests/UseCaseTests/CreateUseCaseTests.swift
Labels: ⚙️ feature

#25 [feat] FetchTasksUseCase
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Source/Domain/Entities/Task.swift
  ProjectManager/ProjectManager/Source/Domain/Entities/TaskEntity.swift
  ProjectManager/ProjectManager/Source/Domain/Entities/Translater.swift
  ProjectManager/ProjectManager/Source/Domain/UseCases/FetchTasksUseCase.swift
Labels: ⚙️ feature

#28 refactor: delegate를 3개로 분리
  ProjectManager/ProjectManager/Source/Domain/UseCases/CreateUseCase.swift
  ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditTaskDelegate.swift
Labels: ⚒️ refactor

#30 refactor: delegate 네이밍 변경
  ProjectManager/ProjectManager/Source/Domain/UseCases/CreateUseCase.swift
  ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditTaskDelegate.swift
Labels: ⚒️ refactor

#33 [refactor] Project Rebuilding
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager.xcodeproj/xcshareddata/xcschemes/ProjectManager.xcscheme
  ProjectManager/ProjectManager/Source/Domain/Entities/Translater.swift
  ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditTaskDelegate.swift
  ProjectManager/ProjectManagerUnitTests/Common/MockTaskRepository.swift
  ProjectManager/ProjectManagerUnitTests/Common/TaskDummy.swift
  ProjectManager/ProjectManagerUnitTests/Common/TaskEntityDummy.swift
  ProjectManager/ProjectManagerUnitTests/TranslaterTests/TranslaterTests.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/CreateUseCaseTests.swift
Labels: ⚒️ refactor

#36 35 단위테스트 deleteusecase 테스트
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManagerUnitTests/Common/TaskDummy.swift
  ProjectManager/ProjectManagerUnitTests/Common/TaskEntityDummy.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/DeleteUseCaseTests.swift
Labels: 🔬test

#40 feature: UpdateUseCase 구현
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Source/Domain/UseCases/UpdateUseCase.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/UpdateUseCaseTests.swift
Labels: ⚙️ feature

#44 refactor: FetchTasksUseCase DidEndEditingTaskDelegate 채택 및 Unit Test 추가
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditingTaskDelegate.swift
  ProjectManager/ProjectManager/Source/Domain/UseCases/DeleteUseCase.swift
  ProjectManager/ProjectManager/Source/Domain/UseCases/FetchTasksUseCase.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/DeleteUseCaseTests.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/FetchTasksUseCaseTests.swift
Labels: ⚒️ refactor, 🔬test

#48 refactor: 삭제된 DidEndDeletingDelegate 구현
  ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditingTaskDelegate.swift
  ProjectManager/ProjectManager/Source/Domain/UseCases/DeleteTaskUseCase.swift
  ProjectManager/ProjectManager/Source/Domain/UseCases/FetchTasksUseCase.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/DeleteTaskUseCaseTests.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/FetchTasksUseCaseTests.swift
Labels: ⚙️ feature, ⚒️ refactor

#53 feature: TaskListViewModel 추가
  ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskListScene/TaskListViewModel.swift
Labels: ⚙️ feature

#50 42 feature taskeditviewmodel 추가
  ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskEditScene/TaskEditViewModel.swift
Labels: ⚙️ feature

#49 41 feature taskcreateviewmodel 추가
  ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskCreateScene/TaskCreateViewModel.swift
Labels: ⚙️ feature

#52 [feature] TaskDetailViewModel 생성
  ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskDetailScene/TaskDetailViewModel.swift
Labels: ⚙️ feature

#54 feature: StateUpdateViewModel 추가
  ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/StateUpdatePopOverScene/StateUpdateViewModel.swift
Labels: ⚙️ feature

#62 feat: Create, Update시 버튼 활성화/비활성화를 위한 Output
  ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskCreateScene/TaskCreateViewModel.swift
  ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskEditScene/TaskEditViewModel.swift
Labels: ⚙️ feature

#65 단위테스트: TaskEditViewModel 테스트
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Source/Domain/UseCases/DefaultUpdateTaskUseCase.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/FetchTasksUseCaseTests.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/UpdateTaskUseCaseTests.swift
  ProjectManager/ProjectManagerUnitTests/ViewModelTests/Mock/UpdateTaskUseCaseMock.swift
  ProjectManager/ProjectManagerUnitTests/ViewModelTests/TaskEditViewModelTests.swift
Labels: 🔬test

#64 56 단위테스트 tasklistviewmodel 테스트
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Source/Domain/UseCases/DefaultDeleteTaskUseCase.swift
  ProjectManager/ProjectManager/Source/Domain/UseCases/DefaultFetchTasksUseCase.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/DeleteTaskUseCaseTests.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/FetchTasksUseCaseTests.swift
  ProjectManager/ProjectManagerUnitTests/ViewModelTests/Mock/DeleteTaskUseCaseMock.swift
  ProjectManager/ProjectManagerUnitTests/ViewModelTests/Mock/FetchTasksUseCaseMock.swift
  ProjectManager/ProjectManagerUnitTests/ViewModelTests/TaskListViewModelTests.swift
Labels: 🔬test

#63 57 단위테스트 taskcreateviewmodel 테스트
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Source/Domain/UseCases/DefaultCreateTaskUseCase.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/CreateTaskUseCaseTests.swift
  ProjectManager/ProjectManagerUnitTests/UseCaseTests/FetchTasksUseCaseTests.swift
  ProjectManager/ProjectManagerUnitTests/ViewModelTests/Mock/CreateTaskUseCaseMock.swift
  ProjectManager/ProjectManagerUnitTests/ViewModelTests/TaskCreateViewModelTests.swift
Labels: 🔬test

#66 단위테스트: TaskDetailViewModel 테스트
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManagerUnitTests/ViewModelTests/TaskDetailViewModelTests.swift
Labels: 🔬test

#67 단위테스트: StateUpdateViewModel 테스트
  ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/StateUpdatePopOverScene/StateUpdateViewModel.swift
  ProjectManager/ProjectManagerUnitTests/ViewModelTests/StateUpdateViewModelTests.swift
Labels: ⚒️ refactor, 🔬test
